# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipelineConnection'
    subscriptionId: '2c9f6c5b-1952-4939-8bc0-89e513de3afe'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRMRG'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/jamilusman/AzureRmPipeline/master/AzureWebApp/main-template.json'
    overrideParameters: '-projectName ARMPipeline'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'